### PR TITLE
Set the language code dynamically based on the current store view

### PR DESCRIPTION
**Pull request by Paulsky**
Please see https://github.com/aleksandar-babic/magento2-GCR/issues/1

### CODE REVIEW

**Comment by Paulsky** [comment]
@aleksandar-babic what do you think?

**Comment by aleksandar-babic** [comment]
> @aleksandar-babic what do you think?

Hey, @Paulsky thanks for the PR.

Looks good, I'll merge.

**Review by aleksandar-babic — APPROVED** [review]
LGTM

**Comment by Paulsky** [comment]
Thank you @aleksandar-babic

**Pull request merged**
